### ISSUE TITLE
Share presets with colleagues

### ISSUE THREAD

**Issue by amenk** [Derkyela/pert-calculator#14]
I want all my colleagues to use these settings... can we make them default or allow GET parameters to share a according URL

![image](https://github.com/Derkyela/pert-calculator/assets/1087128/402ae779-0839-4e58-8e2c-03afd3a179c5)

**Comment by Derkyela** [comment]
I think the default settings are okay as they are. I especially do not want to store anything by default in the local storage due to the dsgvo bla bla about needing the users active okay for it. But I like the idea about sharing them with a team. Via URL would probably be the easiest. I think I'll add a confirmation before using the settings just so the user guides the confirmation of setting them and does not accidentally overwrite their settings.

**Comment by Derkyela** [comment]
@amenk I have implemented this feature. You now have a button to copy a url with the settings stores as parameter:
![image](https://github.com/Derkyela/pert-calculator/assets/42677737/2a41592a-0e43-4c2b-a16d-cb2bb37d4741)

The button only shows if your current settings differ form the default ones. If you open the provided link you will be asked if you want to import the settings with the option to not be asked again. If the settings you are trying to import are the same as the currently active ones nothing will be imported.

I think this is a good solution to share and at the same time protect the users own settings if they have no intention of changing them. As well there are hints during the import that the settings will be stored in local storage (if enabled).
